import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import styles from '../styles/home.module.scss'

import { getPosts } from '../lib/posts'
import Header from '../components/Header'
import Footer from '../components/Footer.js'

export async function getStaticProps(context) {
    let posts = await getPosts()

    return {
        props: {
            posts,
        },
    }
}

export default function Home(props) {
    return (
        <div className={ styles.container }>
            <Head>
                <title>monolith</title>
                {/* <meta name="description" content="Generated by create next app" /> */}
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <Header />

            <main className={ styles.main }>
                <section className={ styles.list }>
                    { props.posts.map(post => {
                        return <Link key={ post.uuid } href={`/${post.slug}`}>
                            <a className={ styles.postLink }>{ post.slug }</a>
                        </Link>
                    })}
                </section>
            </main>

            <Footer />
        </div>
    )
}
